spring:
  application:
    name: mess-management-backend

  datasource:
    url: jdbc:mysql://localhost:3306/mess_management_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

server:
  port: 8080

# JWT Configuration
jwt:
  secret: mySecretKey1234567890abcdefghijklmnopqrstuvwxyz
  expiration-ms: 86400000 # 24 hours

logging:
  level:
    com.messmgmt: DEBUG
    org.springframework.security: DEBUG